### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by arnklint** [paulca/eyeballs.js#3]
I´ve looked through the TODO which has some nice features in it. If I started working on the offline mode for instance, is there any suggestions on how this should function or be implemented? 

Should it automatically switch to the localstorage adapter when offline and then sync when online mode is back on?

**Comment by whitequark** [comment]
I've recently implemented offline mode and sync, you can check it here: http://github.com/whitequark/zomganizer/blob/master/public/app/controllers/sync_controller.js
Shortly, a very stupid server can, apart from authorization, only do one thing: merge JSON objects. Per database model, there is one hash {id=>object} and one array [id]; first contains actual data and second includes all the deleted records. On sync, client compares local and remote arrays, then sends local changes and applies remote changes.
