### ISSUE TITLE
mongoid, rails3, unexpected token ILLEGAL

### ISSUE THREAD

**Issue by zenom** [paulca/eyeballs.js#4]
I have tried to figure this out all day, trying to get a simple rest set back from rails. I tried with include_root_in_json and without.  I consistently get unexpected token ILLEGAL. Everything else seems to be working from what I can tell. It hits the server, I can print out the data on the server as well and going to the url it works fine directly in the rails path (/posts).  

I have tried data like the following:

  [{"post":{"title":"This is a title."}}]

  {"post":{"title":"This is a title."}}

On top of this I am also trying to figure out what to set to point it to a different restful route, so any feedback you can provide me on these would be great.

I have tried master and not with this issue, also included are my script includes.

```
<script src="/javascripts/vendor/jquery/jquery-1.4.2.min.js?1289153289" type="text/javascript"></script> 
<script src="/javascripts/vendor/mustache/mustache.0.3.0.js?1289153289" type="text/javascript"></script> 
<script src="/javascripts/vendor/eyeballs/o_O.js?1289153289" type="text/javascript"></script> 
<script src="/javascripts/vendor/eyeballs/modules/o_O.model.js?1289153289" type="text/javascript"></script> 
<script src="/javascripts/vendor/eyeballs/modules/o_O.validations.js?1289153289" type="text/javascript"></script> 
<script src="/javascripts/vendor/eyeballs/drivers/jquery/adapters/o_O.rest.js?1289153289" type="text/javascript"></script> 
<script src="/javascripts/vendor/eyeballs/drivers/jquery/modules/o_O.controller.js?1289153289" type="text/javascript"></script> 
<script src="/javascripts/vendor/eyeballs/drivers/jquery/modules/o_O.support.js?1289153289" type="text/javascript"></script> 
<script src="/javascripts/vendor/eyeballs/drivers/jquery/modules/o_O.routes.js?1289153289" type="text/javascript"></script> 
<script src="/javascripts/config/routes.js?1289156043" type="text/javascript"></script> 
<script src="/javascripts/config/initializer.js?1289155151" type="text/javascript"></script> 
<script src="/javascripts/app/models/post.js?1289155160" type="text/javascript"></script> 
<script src="/javascripts/app/controllers/posts_controller.js?1289156138" type="text/javascript"></script> 
```

**Comment by paulca** [comment]
Hey,

Where do you get the message? 

Can you post the backtrace from the Rails server log?

—P

**Comment by zenom** [comment]
I am trying to track this down and I _think_ it might be caused because mongoid / mongo returns _id and you are looking for id? When I am looking at the o_O.rest.js, I get the response back, it errors on the JSON.parse.  Still trying to figure out how to best test this.

**Comment by paulca** [comment]
Hmmm.

Where does the "Unexpected token" error happen?
I'm not sure the _id should matter: if id isn't present, o_O.model just assigns a random id.

—P

**Comment by zenom** [comment]
Ok, maybe not, its still dying on the JSON.parse, but I got this back in the console.

Object
id: "1"
title: "More Magic!"

-- here is the /posts/index controller
def index
    render :json => {"id" => "1", "title" => "More Magic!"}
end

-- here is what the log shows for rails
Started GET "/posts" for 127.0.0.1 at Sun Nov 07 15:02:38 -0500 2010
  Processing by PostsController#index as JS
Completed 200 OK in 6ms (Views: 5.8ms)

**Comment by zenom** [comment]
The unexpected token happens on what appears to to be the JSON.parse around line 20 of o_O.rest.js.  

Here is my modified rest.js i was messing with
console.log(response);
var documents = JSON.parse(response);
console.log(documents);

Here is what is spit out in chromes js debug.

XHR finished loading: "http://lvh.me:3000/posts".
o_O.rest.js:19
Object
o_O.rest.js:20
Uncaught SyntaxError: Unexpected token ILLEGAL

So it spits out the "Object" then it doesn't even get to the console.log part to show the documents.

**Comment by paulca** [comment]
If you fancy hopping into #eyeballs on freenode, I'll be around for a bit.

**Comment by zenom** [comment]
This was resolved with the latest commit. The issue was that it was being returned as an object, so a try block was added to not do JSON.parse in the event an object was sent to it.  Other changes were also completed for url etc.
