### ISSUE TITLE
Please change the name of the project to something else.

### ISSUE THREAD

**Issue by clickwhit** [paulca/eyeballs.js#9]
Just really dislike how if I want to use any of these projects or recommend them, I have to tell my colleague "Hey, try out zombie.js for testing or hey, lets use eyeballs.js!" 

There's a line between unconventional naming and being embarrassed when telling others about it.

Here are some suggestions:

o_O.js (pronounced oh-oh)
eep.js
oo.js (pronounced, oh-oh)
peekmvc.js

**Comment by SlexAxton** [comment]
-1

**Comment by billhorsman** [comment]
If a project called 'eyeballs' with the namespace o_O didn't already exist then we'd have to invent it: it's perfect in every way. Let's not slide into blandness.

**Comment by madrobby** [comment]
-1

**Comment by eoin** [comment]
-1

**Comment by paulca** [comment]
Wow. I'm not sure why I didn't receive all these -1s. I was going to say that I'd consider it, but I know where my allegiance lies!
